dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: JgiTft7A5wFOoItbFO0s5URnw/hHmgsRglzr3AlAuk6cNF+CEr+xF8HmPfYrGHGDpGyypKERq603j5ngeLo14np2woyhQnJOEYCVnSm4S7jU/xBqGpKZjsJ3x75WTRLy3wiuT6rc99Po8w1hJUmaJZWSwIQDujOyuXeB1J4YNujvtbLSVm1LgGptGx2G6YB8Py9XDMDqgzW3uNXO6Vit53sfEiL4c1qw5aV7xZwMmck9oFl4tkq7ZIMPWf6dXQvOW1a3FAtgHKzZjXVZg/ozoMr1bpUETzEjKHwchAMeg8aMk+LCM4nOL3mzPGC9ZT+hbajpS+ZtEvF++5rTJFPlLOWQHa/uGYB+VSSN990rIHF9c71979/7+L4KCJelTsx7KDtptKvwpZc5IkcgT/WQOVjfkHa+N5Bl4OHlEKfSax42sI73TugEqdEB0Xmba9Gp8i+glnziUP0H9ge5XH6mojlHH5V+KbW6MzQYTidZxx3D6KV/gXf9HSAJto97bxeM0rpLSSIG+wmuS3u+7Pa5s9zZ/7mkXjyR11r4GG2BAWQCtSHrObPcQ90ZJ1pnbnjbB2L79MkL9DGJm2Uxy9Lshts02ccW8ppChpI0M2nLpjLHXSrtCx+2ye1H4mXtTFarny4DaDIdtAp8ymPV/w+JTkjm10R+fp8djCcMYUX6MRw=
