dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: GVqI0xAX6fdkxTS+Vbvyu6QI+wXixgaupAYnpRWYIwNddTw3CfFXp882HVUuehJwPhjtWkIPXBodWbF7GxCYDlAbsVRFa+x9QylKPB25alqX4Ts1NbG8/9Bvc67CUN5bNPuChWEmMx7E0m1iGnxN6ak4ANCcGj9mj/FBW+dqoxS8TFf7qsygzJGyeiOCtna9n79y7RQy3ftOmrv14AdNT6vS9PAEcwn/iRzVjSajFDucfqK8BZlZAIpLHZXvRK5tTFCbtL7lT1krQtwpJS20ql7lipZqvndZwqHSO41veHDzCWSQo30XZGihS8H0FNKMSDKORGVus9C0G5JQrwXbVqT1Q+HswGnu+O2USPXF2+1WNU0CrmwqDZR+XdcSSq/m9EGW8guBYbitIDNoJvgb89AyuBHD85rRQAfNpjhn5pIjsG83E6QL4aCtf2JjJS4Tp4dK82fMoJFLJS5+rgY0VTJnuLUJaxbDcqK4zm4hYE79h4KuLaJCXYlHDmuYaZg68bdwPk6A77xQTr3x6OaOj5jNrhf9wlSU3r3t0sOP5SB2T88yISMW6NspsBEpsr9Np/5IcNzaFhGABRfmcwzfY8khX54iRmd78Fk+AFVoo9SccsqBW1z9Va6+f/fLR0a2OVo9XDMRXlg81YzVVeT0mLSbz7DtynrSlHMxNGZjG0k=
