dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: G+BFI4bkE5x+BfqaQcfEce5Ffaow37+U6ulFxJUJpjd7XUmZErRlFA20XNZ7YyKxcBfTcScSq4yx7HYAgXNes81gXaRAfZQnGdZCU2Cl2bOVSV5IVBvxbJ6FqUL4PeAz2KmA5oI4QUOSkfj+0WmAU4gdM2otAfUucSzde3nAwBollYoG7LiBFr4Kpy4gX/yvE/hLKrIXjs8AC6TImCdjVmf1g9iLtJa3c78DKlMh7f4YGaYeWBA9DBar8BWIA9zH5cTcWjCZ0bZZZrNOcYRH+eX3Glg2TYkf0Ml7N6X0CP5ya5wM16jz3WPM+SKcCN4YGOx64ZttFHwCDUs6ER6tg9ZHGH65en7y2hWozqSK3H/W1pxHjZl+tHXCHjso35hWbMq9BvLZ74jyjStqd6qSxBRe9S3JCiq3GHoa2pCWMBBiUhR9PJAr2Z57sMSZ7H06lWhdrj4hBtRstb/We7qVqmB61SrQ6hIxKTXjnkUN4EPzue8Vq3EPdqyY2jvc+0ZYHaVq7RVFJgQgSN9RE1U0+3+5ourFx/QICiixRiMFutK5r+N7xbIO6TllU7TkevB/y7oUdPihDYrg1NnBbXsEwQH3zW6AT2DpEfWCwaiueaPTZ9JMy1ki93PuethcGNN4FQWjS9NwDncRDv8tQeueURxvy8qvE8siXjcHxqBxdsI=
