---
- name: Configure MonogDB
  hosts: db
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
        backup: yes
      notify: restart mongod

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted daemon_reload=yes
